spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_ENDPOINT_URL}:3306/${DATABASE_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  config:
    activate:
      on-profile: dev

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: trued

  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 5MB

aws-property:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  aws-region: ap-northeast-2
  s3-bucket-name: ${AWS_S3_BUCKET_NAME}

server:
  port: 8085