name: CD

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy-ci:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: application.yaml 생성
      run: | 
          cd src/main/resources
          echo "${{ secrets.COKOTHON_SERVER_YML }}" > ./application-deploy.yml
      working-directory: ${{ env.working-directory }}

    - name: 빌드
      run: |
          chmod +x gradlew
          ./gradlew build -x test
      working-directory: ${{ env.working-directory }}
      shell: bash


    - name: docker build 가능하도록 환경 설정
      uses: docker/setup-buildx-action@v2.9.1

    - name: docker hub에로그인
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
        password: ${{ secrets.DOCKERHUB_LOGIN_ACCESSTOKEN }}

    - name: docker image 빌드 및 푸시
      run: |
        docker build --platform linux/amd64 -t yejunpark1/cokothonteam5 .
        docker push yejunpark1/cokothonteam5

  deploy-cd:
    needs: deploy-ci
    runs-on: ubuntu-22.04

    steps:    # EC2 인스턴스 내부에서 도커 이미지 다운로드
    - name: 도커 컨테이너 실행
      uses: appleboy/ssh-action@master
      # *-p : Port {외부에서 접속할 포트}:{내부에서 실행되는 포트}로 지정
      with:
        host: ${{ secrets.RELEASE_SERVER_IP }}
        username: ${{ secrets.RELEASE_SERVER_USER }}
        key: ${{ secrets.RELEASE_SERVER_KEY }}
        script: |
          docker rm -f cokothonteam5
          docker image pull yejunpark1/cokothonteam5
          docker run -d --name cokothonteam5 -p 8080:8085 yejunpark1/cokothonteam5
